<a href="https://colab.research.google.com/github/Preetam-R/Machine_Learning/blob/main/mean%2Cmeadia%2Cmode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

arr = np.random.randint(1,500,size = 10)
print(arr)

mean = np.mean(arr)
print("the mean of the give array is:",mean)


[238 154 398 443 463 458 488 304 177 269]
the mean of the give array is: 339.2


In [18]:
arr = np.array([23,45,11,67,92,111,546,24,454,42,1,56,2])

print("the given array is\n",arr)

mdn = np.median(arr)
print("median of given arr is",mdn)

the given array is
 [ 23  45  11  67  92 111 546  24 454  42   1  56   2]
median of given arr is 45.0


In [23]:
!pip install scipy

In [24]:
import statistics as st
from scipy import stats
arr = np.random.randint(1,20,size = 10)
print(arr)

mode = stats.mode(arr)
print(mode)

[ 9  3 15 18  5 13 18 11 11  7]
ModeResult(mode=np.int64(11), count=np.int64(2))
